export const SECTOR_MAP: Record<string, string> = {
  NVDAx: "Technology",
  TSLAx: "Consumer Cyclical",
  AAPLx: "Technology",
  MSFTx: "Technology",
  GOOGLx: "Communication",
  AMZNx: "Consumer Cyclical",
  METAx: "Communication",
  SPYx: "ETF",
  QQQx: "ETF",
  AMDx: "Technology",
  INTCx: "Technology",
  NFLXx: "Communication",
};

const UNDERLYING_SECTOR: Record<string, string> = {
  SNDK: "Technology",
  SPCX: "Industrials",
  MU: "Technology",
  SOXL: "ETF",
  LITE: "Technology",
  MRVL: "Technology",
  SKHY: "Technology",
  INTC: "Technology",
  MSTR: "Financial",
  AAPL: "Technology",
  GOOGL: "Communication",
  CRCL: "Financial",
  NBIS: "Technology",
  PL: "Industrials",
  TSLA: "Consumer Cyclical",
  META: "Communication",
  NVDA: "Technology",
  EWY: "ETF",
  AMD: "Technology",
  COIN: "Financial",
  ORCL: "Technology",
  ONDS: "Industrials",
  DELL: "Technology",
  CSCO: "Technology",
  CRWV: "Technology",
  HIMS: "Healthcare",
  PLTR: "Technology",
  TSM: "Technology",
  QQQ: "ETF",
  HOOD: "Financial",
  AMZN: "Consumer Cyclical",
  SPY: "ETF",
  MSFT: "Technology",
  ARM: "Technology",
  RKLB: "Industrials",
  ASTS: "Communication",
  AVGO: "Technology",
  CBRS: "Technology",
  TQQQ: "ETF",
  ADBE: "Technology",
  IREN: "Technology",
  AAOI: "Technology",
  ASML: "Technology",
  IBM: "Technology",
  XLE: "ETF",
  NFLX: "Communication",
  BMNR: "Technology",
  TER: "Technology",
  USAR: "Materials",
  GME: "Consumer Cyclical",
  LLY: "Healthcare",
  AMAT: "Technology",
  GEV: "Industrials",
  IWM: "ETF",
  BE: "Energy",
  CRWD: "Technology",
  VRT: "Technology",
  ALAB: "Technology",
  APP: "Technology",
  COHR: "Technology",
  TWLO: "Communication",
  BSP: "Technology",
  SHAZ: "Technology",
  ON: "Technology",
  SMCI: "Technology",
};

export function sectorFor(symbol: string): string | undefined {
  if (SECTOR_MAP[symbol]) return SECTOR_MAP[symbol];
  const underlying = symbol.replace(/x$/i, "");
  return UNDERLYING_SECTOR[underlying];
}